
const headers = [
  "क्रम संख्या",
  "परियोजना का नाम",
  "परियोजना अद्यतन स्थिति",
  "कार्यदायी संस्था",
  "परियोजना स्वीकृत होने की तिथि एवं शासनादेश संख्या",
  "परियोजना हेतु शासन द्वारा जारी वित्तीय स्वीकृति का दिनांक एवं शासनादेश संख्या",
  "परियोजना की स्वीकृत लागत",
  "अनुबंध गठन के अनुसार परियोजना पूर्ण करने की तिथि",
  "परियोजना पर अब तक कुल अवमुक्त धनराशि",
  "परियोजना पर अब तक कुल व्यय धनराशि",
  "माइलस्टोन प्रगति %",
  "भौतिक प्रगति %",
  "कार्यदायी संस्था के अनुसार कार्य पूर्ण होने की अनुमानित तिथि",
  "परियोजना में विलम्ब के कारण",
  "पुनरीक्षित स्वीकृति की तिथि",
  "पुनरीक्षित स्वीकृति के अनुसार परियोजना की लागत",
  "पुनरीक्षित स्वीकृति के अनुसार परियोजना को पूर्ण करने की तिथि",
  "विभाग का नाम",
  "परियोजना श्रेणी/योजना का नाम",
  "अनुबंध गठन की तिथि",
  "कार्यदायी संस्था को भूमि उपलब्ध कराने की तिथि",
  "परियोजना अपडेट लाग",
  "परियोजना गैलरी",
  "बैठक निर्देश",
  "बैठक निर्देश अनुपालन",
];

const projects = {
    id: "1",
    projectName: "Carpet City-2 Development",
    projectStatus: "In Progress",
    executingAgency: "BIDA",
    approvalDateAndOrderNumber: "15-05-2023, Order No. 101/2023",
    financialApprovalDateAndOrderNumber: "20-05-2023, Order No. 202/2023",
    approvedProjectCost: "₹100 Crore",
    completionDateAsPerContract: "31-12-2025",
    totalReleasedFunds: "₹50 Crore",
    totalExpenditure: "₹45 Crore",
    milestoneProgress: "50%",
    physicalProgress: "45%",
    estimatedCompletionDateByAgency: "30-06-2025",
    delayReason: "Delay in land acquisition",
    revisedApprovalDate: "01-07-2024",
    revisedProjectCost: "₹110 Crore",
    revisedCompletionDate: "31-12-2026",
    departmentName: "Industrial Development Department",
    projectCategory: "Industrial Area Development",
    contractFormationDate: "01-06-2023",
    landAvailabilityDate: "15-06-2023",
    projectUpdate: "Update 1",
    projectGallery: "Gallery Link 1",
    meetingInstructions: "Instructions 1",
    complianceOfMeetingInstructions: "Compliance 1",
  }

console.log(headers.length);
console.log(Object.keys(projects).length);
